version: '3'
services:
  backend:
    container_name: threetree-backend
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    image: ${DOCKER_HUB_USERNAME}/backend:tag
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}

  frontend:
    container_name: threetree-frontend
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    image: ${DOCKER_HUB_USERNAME}/frontend:tag
    ports:
      - "3000:3000"

  db:
    container_name: threetree-db
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - /data/postgres
    ports:
      - "5532:5432"
