version: '3'
services:
  backend:
    container_name: threetree-backend
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}


  frontend:
    container_name: threetree-frontend
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    ports:
      - "5173:5173"


  db:
    container_name: threetree
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - /data/postgres
    ports:
      - "5532:5432"

