version: "3"
services:
  backend:
    container_name: threetree-backend
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    image: backend:tag
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080" # Host 8080 -> Konténer 8080

  frontend:
    container_name: threetree-frontend
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    image: frontend:tag
    ports:
      - "3000:3000" # Host 3000 -> Konténer 3000

  db:
    container_name: threetree-db
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - /data/postgres
    ports:
      - "5532:5432" # Host 5532 -> Konténer 5432
