spring:
  port: 8080
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/customer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop # vagy "update", ha frissíteni szeretnéd az adatbázist
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
